services:

  medicaldb:
    container_name: medicaldb
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=MedicalDb 
    restart: always
    ports:
      - "5435:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  pgadmin:
    container_name: pgadmin
    environment: 
      - PGADMIN_DEFAULT_EMAIL=m-shafafi@outlook.com
      - PGADMIN_DEFAULT_PASSWORD=M1718993100s!
    restart: always
    ports:
      - "5070:80" 
    volumes:
      - pgadmin_data:/root/.pgadmin

  medicalshop.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "10000:8080"
    depends_on:
      - medicaldb
